# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a27332db889c3b7b8b265335d24d7f642ff7677f55f66169eeb8bac231a0ee5dc0d9f1c329b1a60ed20eb3df53fa47714cc3038647539b0c9069e4891daff296

test:
  secret_key_base: 502d5e58b25ab0124e86f5065bce70380ea332a8ab322b6e787443b44e5255a83b84559187efc5967f8f5342760d9d4bd98dd8f7e13bfd5c88c947c211d0c102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
